# Configuración para Google App Engine - Máxima confiabilidad
runtime: python39
env: standard

# Configuración de instancias para alta disponibilidad
instance_class: F2

automatic_scaling:
  min_instances: 2
  max_instances: 20
  target_cpu_utilization: 0.6
  target_throughput_utilization: 0.6
  max_concurrent_requests: 80
  cool_down_period_sec: 120
  cpu_utilization:
    target_utilization: 0.6
  target_throughput_utilization: 0.6

# Health checks personalizados
readiness_check:
  path: "/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300

liveness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 4
  success_threshold: 2

# Configuración de red y seguridad
network:
  forwarded_ports:
    - 8080
  instance_tag: dashboard-hidrologico-mme

# Variables de entorno
env_variables:
  PYTHONPATH: /app
  FLASK_ENV: production
  PYTHONUNBUFFERED: "1"
  DASH_DEBUG: "False"
  GAE_ENV: standard

# Handlers para manejo de requests
handlers:
- url: /health
  script: auto
  secure: optional
  
- url: /info
  script: auto
  secure: optional

- url: /static
  static_dir: static
  secure: optional
  expiration: 1h

- url: /.*
  script: auto
  secure: always

# Configuración de recursos
resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

# Configuración de logs
beta_settings:
  cloud_sql_instances: ""

# Configuración adicional para producción
includes:
  - env_variables.yaml
